### ISSUE TITLE
Some problems in deployment

### ISSUE THREAD

**Issue by Conchsk** [usnistgov/MDCS#1]
Hello, we want to deploy mdcs-statton here. But I didn't find a deployment guide in project. If I followed the guide in MDCS/docs, I got some problems. 
1. When run celery, there are no module named 'mgi'. 
2. When execute 'python manage.py *****', the console only shows following:
'ERROR : Impossible to init the rules : no such table: auth_group
[21/May/2018 06:03:40] INFO [core_oaipmh_harvester_app.tasks:120] START revoking OAI-PMH scheduled tasks.' 
I want some help. Thanks!

**Comment by bjlNistGitHub** [comment]
Please see the following deployment guide for Windows (posted to our current develop branch at this time).

https://github.com/usnistgov/mdcs-stratton/blob/develop/docs/mdcs-2.0-install-windows.md

Please find a reference to the commit here: 4d838bd
