### ISSUE TITLE
Overwrite templates and types

### ISSUE THREAD

**Issue by AlanReviews** [usnistgov/MDCS#12]
Is it possible to overwrite templates and types, creating multiple versions of a template and type?

**Comment by Guillaume-sousa** [comment]
You can upload templates and manage different versions of the same template via the admin dashboard.

1) Go to the admin dashboard by clicking on "Administration" in the user menu:
<img width="357" alt="Screen Shot 2020-10-02 at 9 39 09 AM" src="https://user-images.githubusercontent.com/8738829/94929549-3b81d480-0493-11eb-9716-d9850e648a70.png">

2) Upload templates/types:
<img width="1675" alt="Screen Shot 2020-10-02 at 9 37 27 AM" src="https://user-images.githubusercontent.com/8738829/94929587-4b011d80-0493-11eb-9f0b-902730282337.png">

3) Click on "Versions" to manage the versions:
<img width="1430" alt="Screen Shot 2020-10-02 at 9 38 10 AM" src="https://user-images.githubusercontent.com/8738829/94929660-6409ce80-0493-11eb-9c74-95d613cf8b02.png">
