### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by dpttw** [usnistgov/MDCS#16]
Hi,

I am installing 2.13.0 with conda 4.8.4 on win 10.  I got an error:
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-install-595neyms\\core-module-chemical-composition-simple-app_d8c248d41cad4ca8be5102d75877df53\\core_module_chemical_composition_simple_app/static/core_module_chemical_composition_simple_app/js/chemical_element_composition_simple.js' 

Any suggestion?

**Comment by Guillaume-sousa** [comment]
Hi @dpttw ,

An issue that we noticed on Win 10 is that a Windows path has a maximum length that seems to be 260 characters. The path from your error is 267 characters long. You can try to move up your installation folder.

**Comment by dpttw** [comment]
Hi Guillaume,

Thanks for the tip.  I downloaded the module from pip and install it locally, which works for me.
