### ISSUE TITLE
miss-matched docs/api notes

### ISSUE THREAD

**Issue by danielsauceda** [usnistgov/MDCS#21]
A minor error in the http://localhost:8000/docs/api implementation notes.

There are some miss matched commands. although there is no loss in functionality.

![2016-05-16-122923_1280x1024_scrot](https://cloud.githubusercontent.com/assets/11530180/15297915/57cb83da-1b62-11e6-9a8d-1a37d4e51bb5.png)

**Comment by Guillaume-sousa** [comment]
The REST API docs have been updated. Thanks for letting us know about this issue.
