### ISSUE TITLE
Type Resolver: All Versions of Types Appear in Dropdown

### ISSUE THREAD

**Issue by WardLT** [usnistgov/MDCS#23]
When resolving types when uploading a new template, all version of a certain type appear in the dropdown menu with the same name

![image](https://cloud.githubusercontent.com/assets/7003149/16280002/c0075142-387a-11e6-9f3e-374f32f0881e.png)

**Comment by Guillaume-sousa** [comment]
Thank you for your feedback. It has been updated to only show the current version of a template/type.
